### ISSUE TITLE
Flickr API Going SSL

### ISSUE THREAD

**Issue by jprlauzier** [dopiaza/DPZFlickr#4]
Flickr will deprecate the non-SSL access on June 27th.

Could it be possible to update the URLs with the SSL ones?

http://code.flickr.net/2014/04/30/flickr-api-going-ssl-only-on-june-27th-2014/

Thanks.

**Comment by dopiaza** [comment]
Yes, that's on my list of things to do.

**Comment by dopiaza** [comment]
This has now been done
